apiVersion: v1
kind: Service
metadata:
  name: mern-backend-svc
  labels:
    app: mern-backend
spec:
  selector:
    app: mern-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
""",
    "k8s/frontend-deployment.yaml": """apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-frontend
  labels:
    app: mern-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern-frontend
  template:
    metadata:
      labels:
        app: mern-frontend
    spec:
      containers:
        - name: frontend
          image: REPLACE_WITH_FRONTEND_IMAGE # e.g. registry.example.com/youruser/mern-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: \"http://mern-backend-svc:5000\"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10