apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mern.fullname" . }}-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "mern.fullname" . }}-frontend
                port:
                  number: {{ .Values.service.frontend.port }}