apiVersion: v1
kind: Service
metadata:
  name: {{ include "mern.fullname" . }}-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: {{ include "mern.fullname" . }}-mongo